from pynput.keyboard import Key
Translate_Keys: dict = {
    "backspace": Key.backspace,
    "caps_lock": Key.caps_lock,
    "delete": Key.delete,
    "enter": Key.enter,
    "esc": Key.esc,
    "insert": Key.insert,
    "num_lock": Key.num_lock,
    "page_down": Key.page_down,
    "page_up": Key.page_up,
    "pause": Key.pause,
    "print_screen": Key.print_screen,
    "scroll_lock": Key.scroll_lock,
    "space": Key.space,
    "tab": Key.tab,
    "down": Key.down,
    "left": Key.left,
    "up": Key.up,
    "right": Key.right,
    "home": Key.home,
    "end": Key.end,
    "shift": Key.shift,
    "shift_l": Key.shift_l,
    "shift_r": Key.shift_r,
    "alt": Key.alt,
    "alt_l": Key.alt_l,
    "alt_r": Key.alt_r,
    "alt_gr": Key.alt_gr,
    "cmd": Key.cmd,
    "cmd_l": Key.cmd_l,
    "cmd_r": Key.cmd_r,
    "ctrl": Key.ctrl,
    "ctrl_l": Key.ctrl_l,
    "ctrl_r": Key.ctrl_r
}